source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftBus_Example', :exclusive => true do
  pod "SwiftBus", :path => "../"
end

target 'SwiftBus_Tests', :exclusive => true do
  pod "SwiftBus", :path => "../"

  
end
